let firstName= 'Anjula';
let lastName = 'Ghale';
let age = 100;
let isMarried = true;
let country = 'Nepal';
let occupation = null; 
console.log(firstName, lastName, age,isMarried);
let myAge = "I am 20 years old.";
let yourAge = "You are 25 years old.";
console.log(myAge);
console.log(yourAge);